on: pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iffy/install-nim@v3.2.2
        with:
          version: stable
      - run: nim r -d:release generate_packages.nim
      - run: ./getmergebase.sh
      - run: nim r -d:ssl -d:release package_scanner.nim packages.json --old=packages_old.json --check-urls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          add: "packages.json"
          default_author: github_actions


