on: pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iffy/install-nim@v3.2.2
        with:
          version: stable

      - run: nim r -d:release generate_packages.nim
      - run: ./getmergebase.sh
      - run: nim r -d:ssl -d:release package_scanner.nim packages.json --old=packages_old.json --check-urls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GIT Commit Build Artifacts (packages.json)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event.pull_request.merged == true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add packages.json
          git commit -m "update packages.json"
          git push

